[package]
name = "eren_render_vulkan_3d"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
eren_render_vulkan_core = { path = "../eren_render_vulkan_core" }
ash = "0.38.0"
thiserror = "2.0.12"
