[package]
name = "eren_3d"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.0"
eren_core = { path = "../eren_core" }
glam = "0.30.3"
gltf = "1.4.1"
image = "0.25.6"
wgpu = "25.0.2"
winit = "0.30.11"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ash = "0.38.0"
