[package]
name = "eren_core"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.23.0"
pollster = "0.4.0"
wgpu = "25.0.2"
winit = "0.30.11"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
