[package]
name = "eren_render_core"
version = "0.1.0"
edition = "2024"

[dependencies]
eren_window = { path = "../eren_window" }
pollster = "0.4.0"
thiserror = "2.0.12"
wgpu = "25.0.2"
winit = "0.30.11"
