[package]
name = "eren_render_vulkan_core"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
eren_window = { path = "../eren_window" }
thiserror = "2.0.12"
winit = "0.30.11"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
native-dialog = "0.9.0"
